/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: c73e10ca2457f41f867107f22fedbd64)
declare namespace Cloudflare {
	interface Env {
		// Chat: DurableObjectNamespace<import("./src/server").Chat>;
		Chat: DurableObjectNamespace<import("./src/server/ai/chat-agent").Chat>;
		AI: Ai;
		GOOGLE_GEMINI_API_KEY: string;
		ASSETS: Fetcher;
		DB: D1Database;  
		FILES: R2Bucket;
	}
}
interface Env extends Cloudflare.Env {}
